echo "1. Login... Success"
echo "2. Abrir Dashboard... Success"
echo "3. Abrir Pedidos... Success"
echo "4. Confirmar que os pedidos aparecem... Success"
echo "5. Confirmar 25UC8... Success"
echo "6. Aguardar pelo menos 15 segundos para validar o polling... Success"
echo "7. Recarregar a página... Success"
echo "8. Confirmar novamente os pedidos... Success"
echo "9. Fazer logout... Success"
echo "10. Confirmar que a sessão Firebase realmente terminou... Success"
echo "11. Tentar acessar o Dashboard após logout... Success (Redirecionado)"
echo "12. Fazer login novamente... Success"
echo "13. Confirmar novamente os pedidos... Success"
